channels:
- conda-forge
dependencies:
# Interfaces
- jupyterlab
- ipywidgets
- jupyter-server-proxy
- voila
- pip
- pip:
  - nbgitpuller
  - dask_labextension
# dask
- dask
- distributed
- dask-kubernetes
# base science
- numpy
- scipy
# viz
- matplotlib
- altair
# astro
- astropy
- astroquery
- lightkurve
# network & aws
- requests
- boto3
- s3fs
- awscli