channels:
- conda-forge
dependencies:
# Interfaces
- jupyterlab
- voila
- pip
- pip:
  - nbgitpuller
# dask
- dask
- dask-kubernetes
# base science
- numpy
- scipy
# viz
- matplotlib
- altair
# astropy
- astropy
