daskKubernetes:
  serviceAccount:
    enabled: true

jupyterhub:
  cull:
    enabled: true
    timeout: 1800 # 30min idleness
  proxy:
    https:
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
      enabled: true
  singleuser:
    memory:
      guarantee: 128M
      limit: 1G
    storage:
      dynamic:
        storageClass: aws-efs