daskKubernetes:
  serviceAccount:
    enabled: true

jupyterhub:
  auth:
    type: github
  cull:
    enabled: true
    timeout: 1800 # 30min idleness
  proxy:
    https:
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
      enabled: true
  singleuser:
    storage:
      dynamic:
        storageClass: aws-efs