{{ if .Values.daskKubernetes.serviceAccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dask-kubernetes
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
# Not actually used, needed until https://github.com/dask/dask-kubernetes/issues/229 is fixed
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dask-kubernetes
subjects:
  - kind: ServiceAccount
    name: dask-kubernetes
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: dask-kubernetes
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dask-kubernetes
  namespace: {{ .Release.Namespace }}
{{ end }}
