daskKubernetes:
  serviceAccount:
    enabled: false

jupyterhub:
  cull:
    enabled: true
    users: true
    timeout: 60 # 10 minutes of idleness
    maxAge: 480 # 8h max
  auth:
    type: tmp
  proxy:
    https:
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
      enabled: true
  singleuser:
    memory:
      guarantee: 128M
      limit: 1G
    storage:
      type: nil