daskKubernetes:
  serviceAccount:
    enabled: true

jupyterhub:
  proxy:
    https:
      letsencrypt:
        contactEmail: yuvipanda@gmail.com
      enabled: true
  singleuser:
    memory:
      guarantee: 512M
      limit: 1G
    serviceAccountName: dask-kubernetes