etcJupyter:
  # Options for Jupyter Notebook itself, set for each user
  jupyter_notebook_config.json: {}

nfsPVC:
  enabled: false
  # If you want a PVC with NFS that can be used to mount home directories
  # nfs:
    # serverIP: # IP of your NFS Server
    # shareName: # Path of your NFS share export

daskKubernetes:
  serviceAccount:
    enabled: false

jupyterhub:
  hub:
    extraConfig:
      01-no-root: |
        # Prevent users from escalating to root
        # Disables functioning of setuid binaries like sudo
        c.KubeSpawner.extra_container_config = {
          'securityContext': {
            'runAsUser': 1000,
            'privileged': False,
            'allowPrivilegeEscalation': False
          }
        }

      02-working-dir: |
        # FIXME: This should be automatically set by repo2docker
        c.KubeSpawner.working_dir = '/home/jovyan'

      03-jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']
        c.Spawner.default_url = '/lab'